In [1]:
import numpy as np 

print(np.ones(3))
print(np.zeros(3))
print(np.random.random(3))

[1. 1. 1.]
[0. 0. 0.]
[0.41048053 0.93534167 0.63969368]


###### 算数的算数运算

In [2]:
data = np.array([1,2])
ones = np.ones(2)

print(data + ones)
print(data - ones)
print(data * ones)
print(data / ones)
print(data * 1.6)

[2. 3.]
[0. 1.]
[1. 2.]
[1. 2.]
[1.6 3.2]


###### 数组的切片操作

In [3]:
print(data.max())
print(data.min())
print(data.sum())
print(data.mean())
print(data.prod())      ### (数据乘法) 计算所有元素的乘积
print(data.std())       ### 标准差

2
1
3
1.5
2
0.5


###### Numpy 中的矩阵操作

In [4]:
np.array([[1,2],[3,4]])   ### 创建

array([[1, 2],
       [3, 4]])

In [5]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.09913149 0.17478006]
 [0.54957352 0.38016502]
 [0.79918625 0.41010255]]


###### Numpy 使用广播规则(broadcast)

In [6]:
data = np.array([[1,2],[3,4],[5,6]])

data + np.ones((3,2))

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

###### .dot()

In [7]:
data = np.array([1,2,3])

np.dot(data,[4,5,6])  ### data = [1 ,2 ,3]   1*4 + 2*5 +3*6 = 32

32

###### 矩阵的切片和聚合

In [24]:
data1 = np.array([[1,2],[3,4],[5,6]])

print(data1[0,1])      ### 格式： data[a：b （row），c : d (columns) ] 
print(data1[1:3])      ### 没有逗号默认 row-> 1:3 ,全列 
print(data1[0:2,0])

2
[[3 4]
 [5 6]]
[1 3]


In [27]:
print(data1.max(axis = 0))     ### 要取数组中最大的值， 则不需要加axis 
print(data1.min(axis = 0))     ### 若要呈现数组中最大的数组 ， 则需要加 axis
print(data1.sum(axis = 0))

print(data1.max(axis = 1))
print(data1.min(axis = 1))
print(data1.sum(axis = 1))

[5 6]
[1 2]
[ 9 12]
[2 4 6]
[1 3 5]
[ 3  7 11]


###### 矩阵的转置和重构

In [29]:
print(data)
print(data.T)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


###### 改变一个维度只需加一个逗号 "，"

In [45]:
np.zeros((4,3,2))   ### np.ones(shape, dtype=None, order='C')
                    ###  4行 三列 两祖

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

###### 均方误差

In [56]:
predictions = np.ones(3)
labels = np.array([1,2,3])

error = (1/3) * np.sum(np.square(predictions - labels))
error

1.6666666666666665